[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"
  
[context.deploy-preview.environment]
  command = "npx prisma migrate deploy"
  

[[plugins]]
package = 'netlify-plugin-prisma-provider'
  [plugins.inputs]
  path = 'prisma/schema.prisma'
  varName = 'postgresql'