[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"
  

[[plugins]]
package = 'netlify-plugin-prisma-provider'
  [plugins.inputs]
  path = 'prisma/schema.prisma'
  varName = 'postgresql'